source 'http://rubygems.org'
gem 'eventmachine', github: "eventmachine/eventmachine"
gem 'em-http-request'
gem 'nokogiri'
gem 'mechanize'
gem 'httpclient'
gem 'sqlite3'
gem 'poltergeist'
gem 'capybara'
gem 'capybara-webkit'
gem 'headless'
