source 'http://rubygems.org'
#gem 'eventmachine', github: "eventmachine/eventmachine"
#gem 'em-http-request'
#gem 'nokogiri'
#gem 'mechanize'
#gem 'httpclient'
gem 'sqlite3'
#gem 'capybara'
#gem 'capybara-webkit'
#gem 'headless'
#gem 'parallel'
